-- ============================================================================
-- IRWIN NATURALS COMES FROM REACHER, NOT EUKA.
--
-- Rashid, 2026-09-23: "there is one brand we have Irwin Naturals, for that
-- brand we have Reacher api not euka ... we need same operations as we are
-- currently doing with euka api ... Please do not disturb anything, just for
-- Irwin Naturals."
--
-- Reacher is a different TikTok Shop affiliate platform, and the Wurx account
-- holds four shops there; Irwin Naturals (shop 12832) is the only one that is
-- also one of our brands. Its figures cannot come from Euka: Irwin has no Euka
-- store at all.
--
-- NOTHING HERE CHANGES AN EXISTING ROW OR AN EXISTING READER. Reacher's
-- per-video ad figures land in the SAME table the screen already reads, so the
-- brand page needs no new query: `euka_ad_totals_for_videos` sums by video id
-- and does not care which platform filed the row. The only additions are a
-- `source` column that defaults to what every existing row already is, and a
-- run log of our own.
-- ============================================================================

-- ---------------------------------------------------------------- provenance --
-- WHICH PLATFORM FILED THIS ROW. Everything in the table today came from Euka,
-- so that is the default and no backfill is needed. It is not part of the key:
-- the same video could in principle be reported by both, and the reader is
-- meant to sum them rather than pick.
alter table public.euka_ad_video_month
  add column if not exists source text not null default 'euka'
  check (source in ('euka', 'reacher'));

comment on column public.euka_ad_video_month.source is
  'Which platform reported this row: euka (every row before 2026-09-23) or reacher (Irwin Naturals). The reader sums regardless; this is for provenance and for cleaning up one platform''s rows without touching the other''s.';

create index if not exists euka_ad_video_month_source_idx
  on public.euka_ad_video_month (source);

-- ------------------------------------------------------------- the run log ---
-- What the Reacher sync did, each time it ran. The Euka side has one of these
-- per store and per unit; Reacher is one shop and a much smaller job, so one
-- row per run is enough to answer "is it working, and what did it change".
create table if not exists public.reacher_sync_runs (
  id               bigint generated by default as identity primary key,
  ran_at           timestamptz not null default now(),
  shop_id          integer not null,
  shop_name        text,
  -- What Reacher had.
  videos_seen      integer not null default 0,
  -- What we filed onto a Paid Collabs row that did not have it.
  videos_filed     integer not null default 0,
  creators_matched integer not null default 0,
  -- Per-video ad spend rows written. Zero while no GMV Max campaign exists.
  spend_rows       integer not null default 0,
  campaigns_seen   integer not null default 0,
  ok               boolean not null default true,
  note             text,
  ms               integer
);

comment on table public.reacher_sync_runs is
  'One row per reacher-sync run: what Reacher held for Irwin Naturals, what was filed onto Paid Collabs rows, and how many ad-spend rows were written. Zero spend rows is the expected answer until a GMV Max campaign is connected on that shop.';

create index if not exists reacher_sync_runs_ran_at_idx
  on public.reacher_sync_runs (ran_at desc);

-- ------------------------------------------------------------------- access --
-- RLS on, deny by default, like every table here.
alter table public.reacher_sync_runs enable row level security;

-- Staff and the read-only Paid Collabs roles may read the log; it is diagnostic
-- and carries no personal data. Nobody writes it but the sync.
drop policy if exists reacher_sync_runs_select_staff on public.reacher_sync_runs;
create policy reacher_sync_runs_select_staff on public.reacher_sync_runs
  for select to authenticated
  using (public.is_collabs_viewer());

-- Grants are explicit, per table, because `Automatically expose new tables` is
-- OFF on this project — which also switches off the default grants to
-- service_role, so the Edge Function would silently see nothing without this.
grant select on table public.reacher_sync_runs to authenticated;
grant all privileges on table public.reacher_sync_runs to service_role;
grant usage, select on sequence public.reacher_sync_runs_id_seq to service_role;
