-- ===========================================================================
-- WurxBase comes home.
--
-- Paid Collabs has been talking to a SEPARATE Supabase project
-- (bnevtdezskftlrjjgbsg) straight from the browser, with a publishable key
-- that ships in our bundle and no authentication of any kind. Rashid has
-- decided there is now one copy of that app and it is ours, so its data moves
-- here and is governed like everything else we own.
--
-- ITS OWN SCHEMA, NOT `public`, and that is the whole trick. Their code says
-- `.from('creators')` in forty-two places and `.from('app_users')` in
-- twenty-four; putting these tables in `public` would either collide with our
-- own names one day or force a rewrite of every call site. A schema means the
-- client is configured once — `{ db: { schema: 'wurxbase' } }` — and not one
-- line of their code changes.
--
-- THEIR `creators` IS NOT OUR CREATORS, and the two must never be merged on a
-- hunch. Theirs is a paid-deal tracker: a brand, a deal string like
-- "$200 for 6", who hired them, and an array of delivered video codes. Ours is
-- a person with a login, an application and a brand hub. Same word, different
-- grain. Anything that wants to join them has to do it deliberately, on
-- TikTok handle or video id, in a view written for the purpose.
--
-- FAITHFUL COPY, WITH ONE DELIBERATE CHANGE. Types are exactly what their
-- database reports — probed column by column against the live project, because
-- their PostgREST refuses the OpenAPI spec to anon and a sample row cannot tell
-- text from date or integer from numeric. The one change: `json` becomes
-- `jsonb`. Every value in those columns is machine-written objects and arrays,
-- so nothing observable changes, and jsonb is what lets us index and constrain
-- these columns later. That "later" is the point of the whole move.
--
-- WHAT THIS MIGRATION DELIBERATELY DOES NOT DO
--
--   * No unique constraint on (action, target) yet. It is the thing that would
--     make the angle-test and contract overwrite bugs IMPOSSIBLE rather than
--     merely unlikely — see PARKED 34 — but their save inserts a new row and
--     then deletes the old ones, so adding it now breaks every save on the day
--     it lands. The constraint arrives with the code change, not before it.
--   * `app_users.password` is copied as it is: PLAINTEXT, and readable by any
--     signed-in staff member. That is exactly as exposed as it is today and no
--     worse, because their login screen still reads it to check a password in
--     the browser. It stops being true in the very next step, when the session
--     comes from our own auth and their login is bypassed entirely. Revoking
--     the column before then would lock the team out of Paid Collabs.
-- ===========================================================================

create schema if not exists wurxbase;

comment on schema wurxbase is
  'WurxBase (Paid Collabs), vendored in from its own Supabase project on '
  '2026-08-28. Kept out of public so their `.from(...)` calls need no rewrite '
  'and can never collide with ours.';

-- PostgREST reaches this schema only once it is added to the exposed list in
-- the project API settings. Usage alone is not enough, but it is required.
grant usage on schema wurxbase to authenticated, service_role;

-- ------------------------------------------------------------------ tables --

-- The paid-deal tracker. 1,249 rows at the time of the move.
create table wurxbase.creators (
  id                bigint generated by default as identity primary key,
  airtable_id       text,                       -- provenance: rows began in Airtable
  created_time      timestamptz,                -- when Airtable first saw it
  inserted_at       timestamptz default now(),  -- when this row was written here
  brand             text,
  name              text,
  whatsapp_number   text,
  deal              text,                       -- free text, e.g. "$200 for 6"
  payment_status    text,
  tiktok_account    text,
  tiktok_account_2  text,
  videos            text,                       -- a status word, not a count
  hiring_date       text,                       -- text in their schema, not date
  deadline          date,                       -- and this one genuinely is a date
  hired_by          text,
  paypal            text,
  zelle             text,
  email             text,
  product           text,
  comments          text,
  category          text,
  status            text,                       -- approved / pending / rejected
  gmv               numeric,
  ad_spent          numeric,
  total_gmv         numeric,
  video_codes       jsonb,                      -- [{video, adCode, auth, ...}]
  monthly           jsonb,                      -- {euka: {at, l30, tier}}
  products          jsonb
);

comment on column wurxbase.creators.hiring_date is
  'Text, not a date, in the source schema. Their code slices it as a string '
  '(`String(c.hiring_date).slice(0,7)`), so converting it to `date` here would '
  'change what that produces. Left as text on purpose.';

comment on column wurxbase.creators.video_codes is
  'The delivered videos for this deal. Joined to our ad figures on the TikTok '
  'video id — see src/routes/admin/collab-ad-math.ts. Rebuilt wholesale by '
  'several of their write paths, which is PARKED 34.';

-- Their audit trail, and also their filing cabinet: creative angle tests,
-- brand contracts and Discovery marks all ride in here as one row per subject,
-- because that project had no DDL access. Ours does, so this is temporary.
create table wurxbase.activity_logs (
  id            bigint generated by default as identity primary key,
  user_id       text,
  user_display  text,
  action        text,
  target        text,
  details       jsonb default '{}'::jsonb,
  created_at    timestamptz default now()
);

comment on table wurxbase.activity_logs is
  'Audit rows AND stored state. action=CREATIVE_ANGLE with target '
  '"Brand::YYYY-MM" is an angle test; BRAND_CONTRACT is a contract; '
  'DISCOVERY_MARK is one creator handle''s outreach state. They rode here '
  'because their project had no DDL access. Now that we own the schema these '
  'should become real tables — but not in the same change that moves them.';

-- Who may use WurxBase, and what they may do. Their `can()` gate reads this.
create table wurxbase.app_users (
  id            text primary key,
  username      text,
  password      text,          -- PLAINTEXT. See the header. Goes away next step.
  role          text,
  display       text,
  brand_access  jsonb default '[]'::jsonb,
  custom_perms  jsonb default '{}'::jsonb,
  last_seen     timestamptz
);

comment on column wurxbase.app_users.password is
  'Plaintext, copied as-is so their login keeps working for the length of one '
  'step. It is no more exposed here than it was in their project, where the '
  'key that could read it shipped in the page source. Delete this column once '
  'the session comes from our own auth.';

-- One global row, id = 1. Brand tab order, hidden brands, the hired-by team.
create table wurxbase.app_settings (
  id             integer primary key,
  brand_order    jsonb,
  hidden_brands  jsonb,
  custom_brands  jsonb,
  hired_by_team  jsonb
);

comment on table wurxbase.app_settings is
  'A single shared row for the whole team, not one row per user. That is why '
  'the missing load guard in scheduleSettingsSave (PARKED 34) can wipe '
  'everybody''s brand order at once.';

create table wurxbase.join_requests (
  id          bigint generated by default as identity primary key,
  name        text,
  email       text,
  username    text,
  status      text,
  created_at  timestamptz default now()
);

create table wurxbase.brand_monthly_budgets (
  id                 uuid primary key default gen_random_uuid(),
  brand              text,
  month              text,               -- 'YYYY-MM'
  budget             numeric,
  content_guide_url  text,
  focus_product_url  jsonb,              -- json in their schema, oddly
  notes              text,
  created_at         timestamptz default now(),
  updated_at         timestamptz default now()
);

create table wurxbase.revoked_sessions (
  session_id  text primary key,
  revoked_by  text,
  revoked_at  timestamptz default now()
);

create table wurxbase.audit_logs (
  id            uuid primary key default gen_random_uuid(),
  actor         text,
  actor_id      text,
  action        text,
  target_type   text,
  target_id     text,
  target_label  text,
  changes       jsonb,
  created_at    timestamptz default now()
);

-- ----------------------------------------------------------------- indexes --
-- Index every common filter and sort from step one, not "later". These are the
-- ones their screens actually issue.

create index creators_brand_idx          on wurxbase.creators (brand);
create index creators_status_idx         on wurxbase.creators (status);
create index creators_hired_by_idx       on wurxbase.creators (hired_by);
create index creators_name_idx           on wurxbase.creators (name);
-- Their brand drilldown filters on brand and then reads video_codes.
create index creators_video_codes_idx    on wurxbase.creators using gin (video_codes);

-- fetchAngles, fetchBrandContracts and the Discovery marks all issue
-- action=eq.X ordered by created_at desc, id asc. One index serves all three.
create index activity_logs_action_target_idx
  on wurxbase.activity_logs (action, target, created_at desc, id);
create index activity_logs_created_at_idx on wurxbase.activity_logs (created_at desc);

create index brand_monthly_budgets_brand_month_idx
  on wurxbase.brand_monthly_budgets (brand, month);

create index audit_logs_created_at_idx    on wurxbase.audit_logs (created_at desc);
create index join_requests_status_idx     on wurxbase.join_requests (status);

-- ------------------------------------------------------------ row security --
--
-- Deny by default on every table, then one policy set. Paid Collabs lives at
-- /admin/collabs, which our router guards with allow={['ops','admin']} — the
-- same pair `public.is_staff()` already answers for. So staff get full use and
-- nobody else gets anything, which is a strict improvement on the old project
-- where an anon key in the page source could read and write all of it.
--
-- DELETE IS GRANTED TO STAFF FOR NOW, and it should not stay that way. Their
-- saves delete as a matter of course — insert the new row, sweep the old ones
-- — so narrowing delete today would break saving for ops. Once the write paths
-- stop deleting (PARKED 34), delete should drop to admin only.

alter table wurxbase.creators              enable row level security;
alter table wurxbase.activity_logs         enable row level security;
alter table wurxbase.app_users             enable row level security;
alter table wurxbase.app_settings          enable row level security;
alter table wurxbase.join_requests         enable row level security;
alter table wurxbase.brand_monthly_budgets enable row level security;
alter table wurxbase.revoked_sessions      enable row level security;
alter table wurxbase.audit_logs            enable row level security;

do $$
declare t text;
begin
  foreach t in array array[
    'creators', 'activity_logs', 'app_users', 'app_settings',
    'join_requests', 'brand_monthly_budgets', 'revoked_sessions', 'audit_logs'
  ]
  loop
    execute format(
      'create policy %I on wurxbase.%I for select to authenticated using (public.is_staff())',
      t || '_select_staff', t);
    execute format(
      'create policy %I on wurxbase.%I for insert to authenticated with check (public.is_staff())',
      t || '_insert_staff', t);
    execute format(
      'create policy %I on wurxbase.%I for update to authenticated using (public.is_staff()) with check (public.is_staff())',
      t || '_update_staff', t);
    execute format(
      'create policy %I on wurxbase.%I for delete to authenticated using (public.is_staff())',
      t || '_delete_staff', t);
  end loop;
end $$;

-- ------------------------------------------------------------------ grants --
--
-- `Automatically expose new tables` is OFF on this project, which also switches
-- off the default grants to service_role. Every table needs both halves spelled
-- out or the Edge Functions that touch them see an empty database and say
-- nothing about it.

do $$
declare t text;
begin
  foreach t in array array[
    'creators', 'activity_logs', 'app_users', 'app_settings',
    'join_requests', 'brand_monthly_budgets', 'revoked_sessions', 'audit_logs'
  ]
  loop
    execute format('grant select, insert, update, delete on table wurxbase.%I to authenticated', t);
    execute format('grant all privileges on table wurxbase.%I to service_role', t);
  end loop;
end $$;

-- Identity columns need their sequence, or an insert fails with a permission
-- error that names the sequence rather than the table and reads like a bug.
grant usage, select on all sequences in schema wurxbase to authenticated, service_role;

-- anon gets nothing. Paid Collabs is behind a login and always will be.
revoke all on all tables in schema wurxbase from anon;
